//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Barangay
{
    using System;
    using System.Collections.Generic;
    
    public partial class CitizenToComplaint
    {
        public int Id { get; set; }
        public string CitizenId { get; set; }
        public string ComplaintId { get; set; }
    
        public virtual Complaint Complaint { get; set; }
        public virtual Citizen Citizen { get; set; }
    }
}
