//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Barangay
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public int Id { get; set; }
        public Nullable<int> CitizenId { get; set; }
        public string DocumentTitle { get; set; }
        public Nullable<System.DateTime> DateIssued { get; set; }
        public string ControlNumber { get; set; }
        public byte[] documentPicture { get; set; }
    
        public virtual Citizen Citizen { get; set; }
    }
}
