//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Barangay
{
    using System;
    using System.Collections.Generic;
    
    public partial class Official
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Position { get; set; }
        public byte[] ProfilePicture { get; set; }
    }
}
