//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Barangay
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string Id { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public bool Rec_Create { get; set; }
        public bool Rec_Edit { get; set; }
        public bool Rec_Delete { get; set; }
        public bool Comp_Create { get; set; }
        public bool Comp_Edit { get; set; }
        public bool Comp_Delete { get; set; }
        public bool IssueDocument { get; set; }
        public bool AddLogin { get; set; }
    }
}
